const canEat = require('../client/src/Utils/canEat');

const userNone = {
  username: 'dumbledore',
  isVegan: false,
  isVegetarian: false,
  isMilkFree: false,
  isEggFree: false,
  isPeanutFree: false,
  isTreenutFree: false,
  isFishFree: false,
  isShellfishFree: false,
  isSoyFree: false,
  isWheatFree: false,
  isGlutenFree: false
};

const userVegan = {
  username: 'vegan',
  isVegan: true,
  isVegetarian: false,
  isMilkFree: true,
  isEggFree: true,
  isPeanutFree: false,
  isTreenutFree: false,
  isFishFree: true,
  isShellfishFree: true,
  isSoyFree: false,
  isWheatFree: false,
  isGlutenFree: false
};

const userGF = {
  username: 'gf',
  isVegan: false,
  isVegetarian: false,
  isMilkFree: false,
  isEggFree: false,
  isPeanutFree: false,
  isTreenutFree: false,
  isFishFree: false,
  isShellfishFree: false,
  isSoyFree: false,
  isWheatFree: true,
  isGlutenFree: true
};

const items = [
  {
    id: 1,
    itemName: 'birthday cake',
    isVegan: false,
    isVegetarian: true,
    isMilkFree: false,
    isEggFree: false,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: false,
    isGlutenFree: false
  },
  {
    id: 2,
    itemName: 'treacle tart',
    isVegan: false,
    isVegetarian: true,
    isMilkFree: false,
    isEggFree: false,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: false,
    isGlutenFree: false
  },
  {
    id: 3,
    itemName: 'sherbert lemon',
    isVegan: true,
    isVegetarian: true,
    isMilkFree: true,
    isEggFree: true,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: true,
    isGlutenFree: false
  },
  {
    id: 4,
    itemName: 'Puking Pastilles',
    isVegan: false,
    isVegetarian: true,
    isMilkFree: true,
    isEggFree: true,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: true,
    isGlutenFree: false
  },
  {
    id: 5,
    itemName: 'fainting fancies',
    isVegan: true,
    isVegetarian: true,
    isMilkFree: true,
    isEggFree: true,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: true,
    isGlutenFree: false
  },
  {
    id: 6,
    itemName: 'chocolate',
    isVegan: false,
    isVegetarian: true,
    isMilkFree: false,
    isEggFree: true,
    isPeanutFree: false,
    isTreenutFree: false,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: true,
    isGlutenFree: true
  },
  {
    id: 7,
    itemName: 'steak and kidney pie',
    isVegan: false,
    isVegetarian: false,
    isMilkFree: false,
    isEggFree: false,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: false,
    isGlutenFree: false
  },
  {
    id: 8,
    itemName: 'cauldron cakes',
    isVegan: false,
    isVegetarian: true,
    isMilkFree: false,
    isEggFree: false,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: false,
    isGlutenFree: false
  },
  {
    id: 9,
    itemName: 'bouillabaisse',
    isVegan: false,
    isVegetarian: false,
    isMilkFree: true,
    isEggFree: true,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: false,
    isShellfishFree: false,
    isSoyFree: true,
    isWheatFree: true,
    isGlutenFree: false
  },
  {
    id: 10,
    itemName: 'pumpkin pasties',
    isVegan: false,
    isVegetarian: true,
    isMilkFree: false,
    isEggFree: false,
    isPeanutFree: false,
    isTreenutFree: false,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: false,
    isGlutenFree: false
  },
  {
    id: 11,
    itemName: 'chocolate frogs',
    isVegan: false,
    isVegetarian: true,
    isMilkFree: false,
    isEggFree: true,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: true,
    isGlutenFree: false
  },
  {
    id: 12,
    itemName: 'corned beef sandwich',
    isVegan: false,
    isVegetarian: false,
    isMilkFree: true,
    isEggFree: true,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: false,
    isGlutenFree: false
  },
  {
    id: 13,
    itemName: "bertie bott's every flavor beans",
    isVegan: false,
    isVegetarian: true,
    isMilkFree: true,
    isEggFree: true,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: true,
    isGlutenFree: true
  },
  {
    id: 14,
    itemName: 'rock cake',
    isVegan: false,
    isVegetarian: false,
    isMilkFree: false,
    isEggFree: false,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: false,
    isGlutenFree: false
  },
  {
    id: 15,
    itemName: 'radish salad',
    isVegan: true,
    isVegetarian: true,
    isMilkFree: true,
    isEggFree: true,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: true,
    isGlutenFree: false
  },
  {
    id: 16,
    itemName: 'butterbeer',
    isVegan: false,
    isVegetarian: true,
    isMilkFree: false,
    isEggFree: true,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: true,
    isGlutenFree: false
  },
  {
    id: 17,
    itemName: 'pumpkin beer',
    isVegan: false,
    isVegetarian: true,
    isMilkFree: true,
    isEggFree: true,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: true,
    isGlutenFree: false
  },
  {
    id: 18,
    itemName: 'boiled potatoes',
    isVegan: false,
    isVegetarian: true,
    isMilkFree: true,
    isEggFree: true,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: true,
    isGlutenFree: false
  },
  {
    id: 19,
    itemName: 'lamb chops',
    isVegan: false,
    isVegetarian: false,
    isMilkFree: true,
    isEggFree: true,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: true,
    isGlutenFree: false
  },
  {
    id: 20,
    itemName: 'Yorkshire pudding',
    isVegan: false,
    isVegetarian: false,
    isMilkFree: false,
    isEggFree: false,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: false,
    isGlutenFree: false
  },
  {
    id: 21,
    itemName: 'bacon and steak',
    isVegan: false,
    isVegetarian: false,
    isMilkFree: true,
    isEggFree: true,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: true,
    isGlutenFree: false
  },
  {
    id: 22,
    itemName: 'roast beef',
    isVegan: false,
    isVegetarian: false,
    isMilkFree: true,
    isEggFree: true,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: false,
    isWheatFree: true,
    isGlutenFree: false
  },
  {
    id: 23,
    itemName: 'bread',
    isVegan: false,
    isVegetarian: true,
    isMilkFree: true,
    isEggFree: false,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: false,
    isGlutenFree: false
  },
  {
    id: 24,
    itemName: 'Beet salad',
    isVegan: false,
    isVegetarian: false,
    isMilkFree: false,
    isEggFree: false,
    isPeanutFree: false,
    isTreenutFree: false,
    isFishFree: false,
    isShellfishFree: false,
    isSoyFree: false,
    isWheatFree: true,
    isGlutenFree: true
  },
  {
    id: 25,
    itemName: 'muggle root beer',
    isVegan: false,
    isVegetarian: false,
    isMilkFree: false,
    isEggFree: false,
    isPeanutFree: false,
    isTreenutFree: false,
    isFishFree: false,
    isShellfishFree: false,
    isSoyFree: false,
    isWheatFree: false,
    isGlutenFree: false
  },
  {
    id: 26,
    itemName: 'water',
    isVegan: true,
    isVegetarian: true,
    isMilkFree: true,
    isEggFree: true,
    isPeanutFree: true,
    isTreenutFree: true,
    isFishFree: true,
    isShellfishFree: true,
    isSoyFree: true,
    isWheatFree: true,
    isGlutenFree: true
  }
];

items.map(item => {
  console.log(
    'omni food',
    canEat(userNone, item) ? 'can eat' : 'cannot eat',
    item.itemName
  );
  console.log(
    'userVegan',
    canEat(userVegan, item) ? 'can eat' : 'cannot eat',
    item.itemName
  );
  console.log(
    'userGF   ',
    canEat(userGF, item) ? 'can eat' : 'cannot eat',
    item.itemName
  );
});
